### ISSUE TITLE
Proposal: Separate session proposals and event schedules

### ISSUE THREAD

**Issue by SeanKilleen** [techtalkdc/MeetupSchedule#5]
It's a little difficult to suggest topics on the sheet that also coordinates the events, because potential speakers may not be quite ready to speak, or their session may depend on the timing pf the next event (which they may not be aware of).

I propose moving to a model similar to [DevOps DC](https://github.com/devopsdc/devopsdc), which has a [speakers.md file](https://github.com/devopsdc/devopsdc/blob/master/speakers.md) where folks can propose topics and a [schedule.md](https://github.com/devopsdc/devopsdc/blob/master/schedule.md) that lists upcoming events so folks can see who's slated to speak.

If folks are open to it (@duluca?), happy to do the PR.

**Comment by duluca** [comment]
Go for it
